framework: mocha
preRun:
     command:
        - npm install typescript
        - npm run compile && npm i --loglevel=error --force
        - export SCRIPT_ID=1EwE84eZCSBPcaAiJzCnDjmxMVnLQrDyhSKq1oZY6q-3x4BIDHgQefCnL
        - export PROJECT_ID=project-id-3961473932623644264
        - npm run pretest
preMerge:
  pattern:
    - "./build/test/files.js"
postMerge:
  pattern:
    - "./build/test/files.js"
postRun:
     command:
        - node --version
configFile: "mocharc.yml"
version: 2.0
